### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by paboman** [spacepxl/ComfyUI-HQ-Image-Save#12]
I am getting an error when installing ComfyUI-HQ-Image-Save module from the custom node manager
even after executing install.bat and restarting ComfyUI the problem persist

![hq image save 2](https://github.com/user-attachments/assets/b9f9c373-0f17-4efe-8b0a-c283878708fc)

![hq image save 1](https://github.com/user-attachments/assets/036a39b9-98ec-4b98-8d05-a7ff19a0fccd)

```
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-03 17:16:57.336966
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\ComfyUI\comfvenv\Scripts\python.exe
** ComfyUI Path: D:\ComfyUI
** Log path: D:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   1.9 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 32706 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI\web
D:\ComfyUI\comfvenv\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save\nodes.py", line 8, in <module>
    import cv2 as cv
ModuleNotFoundError: No module named 'cv2'

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save module for custom nodes: No module named 'cv2'
### Loading: ComfyUI-Manager (V2.51.2)
### ComfyUI Revision: 2737 [d985d1d7] | Released on '2024-10-02'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI-HQ-Image-Save
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
```

What am I doing wrong ?

**Comment by vinavfx** [comment]
https://github.com/spacepxl/ComfyUI-HQ-Image-Save/pull/13

**Comment by spacepxl** [comment]
#13 is merged now, check that you actually have opencv installed, hopefully manager should ensure that it installs now, or you can do it manually:

![image](https://github.com/user-attachments/assets/b300e18d-78bc-4c4b-940e-bd07931fc833)
